### ISSUE TITLE
refresh on any page lealds to "Not found"

### ISSUE THREAD

**Issue by ahovsepy** [hawkular/hawkular-inventory#30]
refresh on any page lealds to "Not found"

![reload_not_found](https://cloud.githubusercontent.com/assets/1850676/6505255/2756f05a-c351-11e4-99c5-d5566edc068c.png)

**Comment by pilhuhn** [comment]
This is a general UI bug that should be reported in HAWKULAR tracker (and I think in fact it may already be HAWKULAR-44)

**Comment by ahovsepy** [comment]
i misses hawkular-44
closing this issue
